Carpenter as a package
arcalot/arcaflow-reusable-workflows pull request #7
Opened 2023-03-10 14:55 UTC by jdowni000

## Changes introduced with this PR

- This change will use carpenter as a package and pull the latest image instead of building it.
- This is utilizing the new [v0.3.0](https://github.com/arcalot/arcaflow-plugin-image-builder/releases/tag/v0.3.0) released recently ( which is latest)
- This is to address [issue](https://github.com/arcalot/arcaflow-plugin-image-builder/issues/42) 
- This has been tested [here](https://github.com/jdowni000/arcaflow-plugin-template-python/actions/runs/4385186181/jobs/7678493877) and image was successfully test, built, and pushed [here](https://quay.io/repository/jdownie/arcaflow-plugin-template-python?tab=tags#:~:text=MANIFEST-,package_17af1ab,-10%20minutes%20ago)

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2023-03-10 15:38 UTC, dustinblack requested changes

2023-03-10 15:38 UTC, dustinblack commented on .github/workflows/carpenter.yaml
> +          docker pull ghcr.io/arcalot/arcaflow-plugin-image-builder:latest
Can we tie this to a release-versioned build instead of latest?

2023-03-10 15:38 UTC, dustinblack commented on .github/workflows/carpenter.yaml
> +            ghcr.io/arcalot/arcaflow-plugin-image-builder:latest build --build --push
Can we tie this to a release-versioned build instead of latest?

2023-03-10 16:11 UTC, BATMAN-JD commented on .github/workflows/carpenter.yaml
> +          docker pull ghcr.io/arcalot/arcaflow-plugin-image-builder:latest
I have updated this

2023-03-10 16:11 UTC, BATMAN-JD commented on .github/workflows/carpenter.yaml
> +            ghcr.io/arcalot/arcaflow-plugin-image-builder:latest build --build --push
I have updated this

2023-03-10 16:28 UTC, dustinblack approved these changes

2023-03-10 16:29 UTC, ghost commented on .github/workflows/carpenter.yaml
> +          docker pull ghcr.io/arcalot/arcaflow-plugin-image-builder:v0.3.0
You don't need to explicitly pull, `docker run` already takes care of this.

2023-03-10 16:29 UTC, ghost commented on .github/workflows/carpenter.yaml
> +        run: |
It would seem that [creating a Dockerfile-based Action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action) could be the way to go here maybe?

2023-03-10 19:35 UTC, mfleader requested changes

2023-03-10 19:35 UTC, mfleader commented on .github/workflows/carpenter.yaml
> +        run: |
Could you elaborate? Do you mean adding the arguments to [carpenter's github action](https://github.com/arcalot/arcaflow-plugin-image-builder/blob/ae68c860326fac69666d56675568a065428faf39/action.yaml), or something else?

2023-03-10 19:59 UTC, ghost commented on .github/workflows/carpenter.yaml
> +        run: |
Hmmm if it is a GHA then why is it being used here by running docker run?

2023-03-13 19:44 UTC, ghost requested changes

2023-03-13 19:44 UTC, ghost commented on .github/workflows/carpenter.yaml
> +        uses: jdowni000/arcaflow-reusable-workflows/.github/workflows/action.yaml@package
Replace before merging please :)

2023-03-14 19:10 UTC, closed without merging